// <auto-generated />
using System;
using ExaminerHub.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExaminerHub.Infrastructure.Migrations
{
    [DbContext(typeof(ExaminerHubDbContext))]
    [Migration("20260711174918_SeedRealisticSession")]
    partial class SeedRealisticSession
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExaminerHub.Domain.Entities.Centre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Centres");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Address = "Murcia",
                            ContactEmail = "admin@kensite.example",
                            ContactName = "Centre Administrator",
                            ContactPhone = "",
                            Name = "Kensington Site"
                        });
                });

            modelBuilder.Entity("ExaminerHub.Domain.Entities.ExamAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PairCount")
                        .HasColumnType("int");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TrioCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("ExamAssignments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddd01"),
                            Level = "FCE FS",
                            PairCount = 3,
                            SessionId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            TrioCount = 1
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddd02"),
                            Level = "PET FS",
                            PairCount = 9,
                            SessionId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            TrioCount = 0
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddd03"),
                            Level = "PET",
                            PairCount = 4,
                            SessionId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            TrioCount = 0
                        });
                });

            modelBuilder.Entity("ExaminerHub.Domain.Entities.Examiner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRemote")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Examiners");
                });

            modelBuilder.Entity("ExaminerHub.Domain.Entities.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Name = "Room 1"
                        });
                });

            modelBuilder.Entity("ExaminerHub.Domain.Entities.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeSpan>("ArrivalTime")
                        .HasColumnType("time");

                    b.Property<Guid>("CentreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeSpan>("ExpectedFinishTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("FirstCandidateTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsRemotePartner")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartnerExaminerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SessionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ZoomLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CentreId");

                    b.HasIndex("RoomId");

                    b.ToTable("Sessions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            ArrivalTime = new TimeSpan(0, 9, 0, 0, 0),
                            CentreId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            ExpectedFinishTime = new TimeSpan(0, 14, 10, 0, 0),
                            FirstCandidateTime = new TimeSpan(0, 9, 30, 0, 0),
                            IsRemotePartner = false,
                            Notes = "Arrive 30 minutes before the first candidate.",
                            PartnerExaminerName = "Gemma",
                            RoomId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            SessionDate = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ZoomLink = ""
                        });
                });

            modelBuilder.Entity("ExaminerHub.Domain.Entities.ExamAssignment", b =>
                {
                    b.HasOne("ExaminerHub.Domain.Entities.Session", "Session")
                        .WithMany("ExamAssignments")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("ExaminerHub.Domain.Entities.Session", b =>
                {
                    b.HasOne("ExaminerHub.Domain.Entities.Centre", "Centre")
                        .WithMany()
                        .HasForeignKey("CentreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExaminerHub.Domain.Entities.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Centre");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("ExaminerHub.Domain.Entities.Session", b =>
                {
                    b.Navigation("ExamAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
